### ISSUE TITLE
webpageのslackへのリンク切れ

### ISSUE THREAD

**Issue by u-kan** [productmanagersjapan/productmanagersjapan.github.io#5]
はじめまして、メルカリでプロデューサーインターンをしているkanです。

slackに参加したいのですがwebpageからいくとリンクが切れていて参加ができず、修正していただくことは可能でしょうか。

![product_managers_japan__pmjp_](https://user-images.githubusercontent.com/12508770/37883759-3afc2fa6-30e7-11e8-81f3-44afecaa7bcf.jpg)

よろしくお願いします！

**Comment by fullvirtue** [comment]
確認しました。URL自体はあっているのですが、pmjp用の herokuapp 自体が落ちちゃっている（消された？）ようですね... @kentaro

**Comment by kyoh86** [comment]
ぜひ参加したいと考えており、別の方法でもご案内いただけないでしょうか。

**Comment by ninjinkun** [comment]
@kyoh86 招待しました！

リンク切れは週末に直しておきます。

**Comment by ninjinkun** [comment]
こちら @kentaro に直して頂きました
